#.travis.yml

language: node_js
node_js:
  - "6.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g gh-pages

script:
  - ng build --prod
  - ng build --prod --base-href "https://Kasunjith-Bimal.github.io/CIAngular/"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - gh-pages -d dist

notifications:
  email:
    on_failure: change
    on_success: change